### ISSUE TITLE
verbatim popup with shiny validation or red error for disabled

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.widgets#102]
This used to come about on the mmrm module until it was fixed

![image](https://user-images.githubusercontent.com/15201933/199995175-37eed782-b08c-4165-bb6f-ec023901853d.png)

Simpler reprex:

![image](https://user-images.githubusercontent.com/15201933/199993391-7c16218d-79d3-420e-8f10-6799111df10f.png)

```
library(teal.code)
library(teal.widgets)
library(shiny)

ui <- fluidPage(
  verbatim_popup_ui("pop", "Warnings")
)

server <- function(input, output, session) {


  disabled <- reactive({
    validate(need(FALSE, "This is a validation but it is being shown!"))
    FALSE
  })

  verbatim_popup_srv(
    "pop",
    title = "boo",
    verbatim_content = reactive("Hello"),
    disabled = disabled
  )
}

shinyApp(ui, server)

```

Also the case if disabled produces a red error?

**Comment by nikolas-burkoff** [comment]
Something like this might work:

```
verbatim_popup_ui <- function(id, button_label, type = c("button", "link"), ...) {
  checkmate::assert_string(id)
  checkmate::assert_string(button_label)

  ui_function <- switch(match.arg(type),
    "button" = shiny::actionButton,
    "link" = shiny::actionLink,
    stop("Argument 'type' should be 'button' or 'link'")
  )

  ns <- shiny::NS(id)
  ui_args <- list(
    inputId = ns("button"),
    label = button_label
  )


  shiny::tagList(
    shiny::singleton(
      shiny::tags$head(shiny::includeScript(system.file("js/verbatim_popup.js", package = "teal.widgets")))
    ),
    do.call(ui_function, c(ui_args, list(...))),
    # this is dummy output - see the comment in srv
    shiny::uiOutput(ns("disable_controller"), inline = TRUE, style = "font-size:0px")
  )
}
```

**Comment by donyunardi** [comment]
I see the same behavior in QQ Plot under tm_g_distribution:

![image](https://user-images.githubusercontent.com/8597300/200077643-08c584d4-76ba-443d-9b49-736d3646eaca.png)

Looking at `?validate` help info, it does say:
```
If you use validate() in a reactive(), validation failures will automatically propagate to outputs that use the reactive.
```

Hiding the message by setting the font-size to 0 definitely works.

**Comment by mhallal1** [comment]
@nikolas-burkoff I tested out with different options but it seems that setting the font size to 0 in the style is the only working solution for now.

**Comment by donyunardi** [comment]
Acceptance Criteria:
* Validation error should not appear in Show Warnings and Show R Code button (verbatim_popup_*).
