### ISSUE TITLE
Plot with settings UI tests - shinytest2

### ISSUE THREAD

**Issue by gogonzo** [insightsengineering/teal.widgets#109]
Currently in the tests of pws and tws we use shinytest2. The tests covers everything but indirectly as some of the events are triggered by changing inputs values directly (by $setInputs) instead of ui interaction ($click). 
I propose to revisit what is possible to $click and perhaps to use shiny::testServer if we can't really make those clicks.

**Comment by Polkas** [comment]
With $click we could not support double click, hover or select area. So we need a $click and js combo if possible or stay with setInputs somewhere.
