### ISSUE TITLE
plot_with_settings: test server

### ISSUE THREAD

**Issue by mhallal1** [insightsengineering/teal.widgets#113]
Please visit `plot_with_settings` and add server unit tests before starting with this task https://github.com/insightsengineering/teal.widgets/issues/109

-Make sure to test the functions `print_plot` and object `plot_reactive` which do not need to be tested on a UI level.

**Comment by gogonzo** [comment]
Please consider [these comments](https://github.com/insightsengineering/teal.widgets/pull/94#pullrequestreview-1194346023)

**Comment by Polkas** [comment]
Summary from https://github.com/insightsengineering/teal.widgets/pull/94#pullrequestreview-1194346023

-  change plot width and height test -  Values of the inputs are set and then they are checked whether they were checked. In this test we actually should check whether file has been downloaded if the file has expected name, width and height https://github.com/insightsengineering/teal.widgets/pull/94#discussion_r1032391669
- height in modal: same inputs are changed multiple times. I'd suggest to set them once and optimally with the app$click https://github.com/insightsengineering/teal.widgets/pull/94#discussion_r1032394969
- plot_with_settings: download functionality ggplot2 - This test doesn't test anything, it just changes the values of the inputs and checks if the inputs are set  https://github.com/insightsengineering/teal.widgets/pull/94#discussion_r1032397960
- plot_data has been testes in the previous test_that - `# check if outputs are reactive
  for (react_i in vals$export$"plot_data") {
    testthat::expect_true(is(react_i, "reactive"))
  }` https://github.com/insightsengineering/teal.widgets/pull/94#discussion_r1032400922
- naming plot_with_settings - click functionalities ggplot2 -> plot_with_settings: returns a reactive consistent with inputs configuration; plot_with_settings: output is returned -> plot_with_settings: renders expected image https://github.com/insightsengineering/teal.widgets/pull/94#discussion_r1032400060 https://github.com/insightsengineering/teal.widgets/pull/94#discussion_r1032401752

**Comment by Polkas** [comment]
Comments:

even empty (NULL) lot has some base64
```
library(shiny)

ui <- fluidPage(
  plotOutput("ss")
)

server <- function(input, output, session) {
  output$ss <- renderPlot(NULL)
}

shinyApp(ui, server)
```

**Comment by Polkas** [comment]
Plan for further work:

- Regular testthat for separate utils functions.
- We need a regular testServer tests which are lighter and could cover most of the cases.
- Then we need to think about UI tests with shinytest2 but it has own limitations. Even download functionality seems to be able to be test with testServer. The print screen test still could be valuable here.
