### ISSUE TITLE
Rstudio and plot_with_settings broken pdf download

### ISSUE THREAD

**Issue by Polkas** [insightsengineering/teal.widgets#120]
@mhallal1 and @chlebowa confirm that on their setup and only inside RStudio, they can not download the pdf file with plot with settings. It is important to note that the problem not exists in the regular R GUI session or cmd.
We should investigate the source of the problem.

**Comment by donyunardi** [comment]
Tested with 4.3.2 locally in VSCode and it also works fine.
Let's close this for now.
