### ISSUE TITLE
plot with settings clicking on icons before graph loads

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.widgets#137]
Choose a module which takes a little time to load (e.g. from tmc)

Clicking on the icons before the plot loads can 
a) crash the app
![image](https://user-images.githubusercontent.com/15201933/210544969-1ba7873d-6f26-4e5c-9376-0afd82d40900.png)

b) produce red errors
![image](https://user-images.githubusercontent.com/15201933/210544810-da73ffa0-8549-4675-9c67-a8f2b48d99dc.png)

**Comment by donyunardi** [comment]
I picked three random tm functions from tmc and I don't see this behavior anymore.
