### ISSUE TITLE
printing ggplot objects to R Console inside plot_with_settings 

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/teal.widgets#14]
<REDACTED>NEST/teal.devel/pull/591

We always not taking care about the fact that we are printing ggplots to the R consoles inside `plot_with_settings `. This occurs even before merging pull/591. For me it is not a problem although one thing to thing is that the plots are not printed always so we have some random externatilites.

@pawelru 

Provenance: 
```
Creator: Polkas
```

**Comment by nikolas-burkoff** [comment]
@Polkas is this still an issue?

**Comment by gogonzo** [comment]
Closed with https://github.com/insightsengineering/teal.code/pull/124
