### ISSUE TITLE
Should `rtables` be in Imports rather than Suggests?

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.widgets#154]
> Judging from this line:
> https://github.com/insightsengineering/teal.widgets/blob/5c1bc697a2c422e6041cbb85bf80614316b83adb/R/table_with_settings.R#L78-L80
> 
> and several other lines that is using rtables function in `basic_table_args.R`, it sounds plausible to move rtables from Suggest to Imports.
> 
> I'll open an issue so we can discuss and not holding up this PR.
> 
> 

_Originally posted by @donyunardi in https://github.com/insightsengineering/teal.widgets/pull/153#discussion_r1196888497_

**Comment by donyunardi** [comment]
@m7pr provided great context why we should keep it in Suggests, which I agree:
https://github.com/insightsengineering/teal.widgets/pull/153#discussion_r1196941298

Another suggestion that he made (which I also agree with):
> or we should add
> 
> ```
>   if (!requireNamespace("rtables", quietly = TRUE)) {
>     stop("package rtables is required, please install")
>   }
> ```
> 
> at the beginning of `basic_table_args` so there is the same information and consistency with `table_with_settings`. Then if someone does not uses tables/rtables then he/she does not need to install rtables to use teal.widgets

**Comment by m7pr** [comment]
proposed #155

**Comment by donyunardi** [comment]
Found an old issue to support keeping rtables in Suggets (and it's exactly as @m7pr predicted): https://github.com/insightsengineering/teal.widgets/issues/134

**Comment by pawelru** [comment]
To me, a package can be in suggests only if there is a non-pkg dependent valid path available that leads to a function _success_ (return or a desired side effect). Something like below:
```
x <- 1
if (is_package_available("foo")) {
  x <- foo::bar(x)
}
return (x)
```
A good example can be found [here](https://github.com/insightsengineering/teal.code/blob/89f07c138f43d7fadaf8a03f8d46f211e3e6720d/R/qenv-eval_code.R#L96-L102)

Hard stop if package is not available is definitely not a valid path leading to a _success_. Therefore I consider the current state as incorrect.

**Comment by m7pr** [comment]
@donyunardi #134 was valid on the day it was created, but may not be valid anymore as `rtables` is used in more places than one function now.

@pawelru your idea is cool, we can extend those functions so that they have different behavior, depending on whether you have `rtables` installed or not, but this is poor approach for the reproducibility as the code will have different effect, depending 
on the environment in which it was run (depending on whether rtables is installed or not). 

**I think we can bring `rtables` to Imports, if this is used in 3 functions and let's move on!**

**Comment by m7pr** [comment]
Yes @donyunardi . I just closed the PR

**Comment by pawelru** [comment]
> I'm just following up on an email I previously sent to you. I understand that you are busy, but I would appreciate it if you could review the email and respond to me as soon as you can.

This is an universal truth and my idea does not change it. If you call `foo::bar()` it might have different behaviour from within environment with `foo@1.2.3` installed compared to the environment with `foo@2.3.4`. For reproducibility you have to include code, R env and also sys env (as you pointed in a separate discussion).

**Comment by donyunardi** [comment]
Thanks guys.
