### ISSUE TITLE
Should `plot_with_settings` still have "Draft" on the output?

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/teal.widgets#48]
FYI @kumamiao 

https://github.com/insightsengineering/teal.widgets/blob/11d7f6f3608db3f451763837d7481b8e356c286d/R/plot_with_settings.R#L514

![image](https://user-images.githubusercontent.com/15201933/171367215-8ba0b70f-d54d-4040-8ab8-e5f491e502fc.png)

**Comment by nikolas-burkoff** [comment]
Worth noting https://github.com/insightsengineering/teal.widgets/blob/main/R/plot_with_settings.R#L517 - if there are changes that allow base graphics to be downloaded that should be done

**Comment by donyunardi** [comment]
### Acceptance Criteria
* Remove the "Draft" word in the plot
