### ISSUE TITLE
Investigate why disable/enable is not working for pickerInput created by optionalInput

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/teal.widgets#8]
We found out that `toggleState`/`disable`/`enable` events in `shinyjs` for an inputs created via `teal::optionalInput` (that internally creates `shinyWidgets::pickerInput`) seem to not work.
On contrary `toggle`/`hide`/`show` is working correctly.

The goal of this task is to investigate the reason and try to fix it. Maybe it has been already resolved so please also check the newest version of `shinyWidgets` package

Provenance: 
```
Creator: pawelru
```

**Comment by nikolas-burkoff** [comment]
@asbates I think this (very old) issue is related to what you've been investigating?

**Comment by asbates** [comment]
@nikolas-burkoff Yes! Very similar to #106. There's some detail there different than here. Maybe we close one of them and add a comment to review the other?

**Comment by donyunardi** [comment]
#106 has more content so I'm closing this and bring over the comment to 106

Dup of #106
